# MegaLinter configuration - https://oxsecurity.github.io/megalinter/latest/
APPLY_FIXES: none
DEFAULT_BRANCH: main
REPORT_OUTPUT_FOLDER: none
VALIDATE_ALL_CODEBASE: false

ENABLE:
  - TYPESCRIPT
  - CSS
  - MARKDOWN
  - JSON
  - YAML
  - JAVASCRIPT
  - ACTION
  - REPOSITORY
  - HTML
  - BASH
  - SPELL

DISABLE_LINTERS:
  - COPYPASTE
  - SPELL_CSPELL

TYPESCRIPT_ES_CONFIG_FILE: eslint.config.js
CSS_STYLELINT_CONFIG_FILE: .stylelintrc.json
YAML_PRETTIER_CONFIG_FILE: .prettierrc
JSON_PRETTIER_CONFIG_FILE: .prettierrc
JAVASCRIPT_ES_CONFIG_FILE: eslint.config.js

REPOSITORY_TRUFFLEHOG: true
REPOSITORY_GITLEAKS: true
REPOSITORY_SECRETLINT: true
REPOSITORY_DEVSKIM: true
REPOSITORY_CHECKOV: false
REPOSITORY_TRIVY: false
