export interface ComponentDoc {
  name: string;
  description: string;
  category: 'primitive' | 'layout' | 'composite';
  features: string[];
  variants: string[];
  props: Array<{ name: string; type: string; default?: string; description: string }>;
  cssVars: Array<{ name: string; description: string }>;
}

export const COMPONENT_DATA: ComponentDoc[] = [
  {
    name: 'Alert',
    description: 'A contextual notification banner with multiple severity levels, dismissible support, and auto-dismiss.',
    category: 'composite',
    features: ['Multiple severity variants', 'Optional icon per variant', 'Dismissible with close button', 'Auto-dismiss timer', 'Title and body content'],
    variants: ['warning', 'caution', 'alert', 'success', 'info', 'notification'],
    props: [
      { name: 'variant', type: 'string', default: 'info', description: 'The visual variant of the alert' },
      { name: 'title', type: 'string', description: 'Optional title text for the alert' },
      { name: 'dismissible', type: 'boolean', default: 'false', description: 'Whether the alert can be dismissed' },
      { name: 'onDismiss', type: '() => void', description: 'Callback fired when the alert is dismissed' },
      { name: 'autoDismiss', type: 'number', description: 'Time in milliseconds before auto-dismissal' },
      { name: 'icon', type: 'boolean', default: 'true', description: 'Whether to show the variant icon' },
      { name: 'children', type: 'ReactNode', description: 'The content of the component' },
    ],
    cssVars: [
      { name: '--azimuth-color-border', description: 'Alert border color' },
      { name: '--azimuth-color-surface', description: 'Alert background color' },
      { name: '--azimuth-color-text', description: 'Alert text color' },
      { name: '--azimuth-color-text-secondary', description: 'Alert body text color' },
    ],
  },
  {
    name: 'Avatar',
    description: 'An image avatar with automatic initials fallback on load failure.',
    category: 'composite',
    features: ['Image display with fallback initials', 'Multiple sizes from xs to xl', 'Square or circular shape', 'Error state handling'],
    variants: ['xs', 'sm', 'md', 'lg', 'xl'],
    props: [
      { name: 'src', type: 'string', description: 'The image source URL' },
      { name: 'alt', type: 'string', description: 'Alt text for the image' },
      { name: 'fallback', type: 'string', description: 'Text used to generate initials when the image fails to load' },
      { name: 'size', type: 'string', default: 'md', description: 'The size of the avatar' },
      { name: 'square', type: 'boolean', default: 'false', description: 'Whether to render a square avatar' },
    ],
    cssVars: [
      { name: '--azimuth-color-primary', description: 'Initials text color' },
      { name: '--azimuth-color-primary-subtle', description: 'Avatar background color' },
    ],
  },
  {
    name: 'Badge',
    description: 'A small status indicator label used to highlight counts or states.',
    category: 'composite',
    features: ['Multiple color variants', 'Compact inline display', 'Semantic color coding'],
    variants: ['neutral', 'accent', 'success', 'warning', 'danger', 'info'],
    props: [
      { name: 'variant', type: 'string', default: 'neutral', description: 'The visual variant of the badge' },
      { name: 'children', type: 'ReactNode', description: 'The content of the component' },
    ],
    cssVars: [
      { name: '--azimuth-radius-full', description: 'Badge border radius' },
      { name: '--azimuth-fs-xs', description: 'Badge font size' },
    ],
  },
  {
    name: 'Breadcrumbs',
    description: 'A navigation trail showing the current page location within the site hierarchy.',
    category: 'composite',
    features: ['Collapsible with ellipsis when exceeding max items', 'Customizable separator', 'ARIA navigation landmark with current page indication'],
    variants: [],
    props: [
      { name: 'items', type: 'Array<{ label: string; href?: string }>', description: 'Array of breadcrumb items with label and optional href' },
      { name: 'separator', type: 'string', default: '/', description: 'Custom separator string between items' },
      { name: 'maxItems', type: 'number', default: '0', description: 'Maximum number of items before collapsing' },
      { name: 'children', type: 'ReactNode', description: 'The content of the component' },
    ],
    cssVars: [
      { name: '--azimuth-color-primary', description: 'Link color' },
      { name: '--azimuth-color-text-muted', description: 'Separator color' },
      { name: '--azimuth-color-text-secondary', description: 'Inactive item color' },
    ],
  },
  {
    name: 'Button',
    description: 'A styled button component with multiple visual variants and size options.',
    category: 'primitive',
    features: ['Multiple style variants including primary, secondary, tertiary, link, and danger', 'Three sizes (sm, md, lg)', 'Icon support with left/right positioning', 'Icon-only mode with accessible label', 'Full-width option', 'Flat variant via theme'],
    variants: ['primary', 'secondary', 'tertiary', 'link', 'danger'],
    props: [
      { name: 'variant', type: 'ButtonVariant', default: 'primary', description: 'The visual style variant' },
      { name: 'size', type: 'string', default: 'md', description: 'The size of the button' },
      { name: 'icon', type: 'ReactNode', description: 'Optional icon element to display alongside the label' },
      { name: 'iconPosition', type: 'string', default: 'left', description: 'Where to position the icon relative to the label' },
      { name: 'fullWidth', type: 'boolean', default: 'false', description: 'Whether the button expands to fill its container width' },
      { name: 'disabled', type: 'boolean', description: 'Whether the button is disabled' },
      { name: 'children', type: 'ReactNode', description: 'The content of the component' },
    ],
    cssVars: [
      { name: '--azimuth-color-primary', description: 'Primary button background' },
      { name: '--azimuth-color-on-primary', description: 'Primary button text color' },
      { name: '--azimuth-color-surface', description: 'Secondary button background' },
      { name: '--azimuth-color-border', description: 'Button border color' },
      { name: '--azimuth-radius-md', description: 'Button border radius' },
    ],
  },
  {
    name: 'Calendar',
    description: 'A full month-view date picker with navigation and keyboard support.',
    category: 'composite',
    features: ['Month navigation with prev/next buttons', 'Controlled or uncontrolled value', 'Date range limits via min/max date', 'Week number display option', 'Locale-aware day names', 'Keyboard navigation'],
    variants: [],
    props: [
      { name: 'value', type: 'Date', description: 'The controlled selected date' },
      { name: 'defaultValue', type: 'Date', description: 'The default selected date (uncontrolled)' },
      { name: 'onChange', type: '(date: Date) => void', description: 'Callback fired when a date is selected' },
      { name: 'minDate', type: 'Date', description: 'Minimum selectable date' },
      { name: 'maxDate', type: 'Date', description: 'Maximum selectable date' },
      { name: 'showWeekNumbers', type: 'boolean', default: 'false', description: 'Whether to show week numbers' },
      { name: 'locale', type: 'string', description: 'Locale for formatting weekday names' },
    ],
    cssVars: [
      { name: '--azimuth-color-primary', description: 'Selected day background' },
      { name: '--azimuth-color-on-primary', description: 'Selected day text color' },
      { name: '--azimuth-color-surface-hover', description: 'Day hover background' },
    ],
  },
  {
    name: 'Card',
    description: 'A content container with optional header, footer, and expandable body.',
    category: 'composite',
    features: ['Header and footer slots', 'Collapsible/expandable body', 'Subcomponents: Header, Footer, Title, Description, Content', 'Controlled or uncontrolled expansion'],
    variants: [],
    props: [
      { name: 'header', type: 'ReactNode', description: 'Header content rendered above the body' },
      { name: 'footer', type: 'ReactNode', description: 'Footer content rendered below the body' },
      { name: 'expandable', type: 'boolean', default: 'false', description: 'Whether the card body is collapsible' },
      { name: 'defaultExpanded', type: 'boolean', default: 'true', description: 'Whether the card is expanded by default' },
      { name: 'children', type: 'ReactNode', description: 'The content of the component' },
    ],
    cssVars: [
      { name: '--azimuth-color-border', description: 'Card border color' },
      { name: '--azimuth-color-surface', description: 'Card background' },
      { name: '--azimuth-color-text', description: 'Card text color' },
      { name: '--azimuth-radius-md', description: 'Card border radius' },
    ],
  },
  {
    name: 'Carousel',
    description: 'A slideshow component with auto-play, dot indicators, and arrow controls.',
    category: 'composite',
    features: ['Auto-play with configurable interval', 'Dot indicators for slide navigation', 'Arrow controls for prev/next', 'Looping or non-looping modes', 'Pauses on hover', 'Respects prefers-reduced-motion'],
    variants: [],
    props: [
      { name: 'children', type: 'ReactNode', description: 'The slides of the carousel' },
      { name: 'autoPlay', type: 'boolean', default: 'false', description: 'Whether the carousel auto-advances' },
      { name: 'interval', type: 'number', default: '5000', description: 'Time in milliseconds between auto-advances' },
      { name: 'showDots', type: 'boolean', default: 'true', description: 'Whether to show dot indicators' },
      { name: 'showArrows', type: 'boolean', default: 'true', description: 'Whether to show arrow controls' },
      { name: 'loop', type: 'boolean', default: 'true', description: 'Whether the carousel wraps around' },
    ],
    cssVars: [
      { name: '--azimuth-color-primary', description: 'Active dot color' },
      { name: '--azimuth-color-surface', description: 'Arrow button background' },
      { name: '--azimuth-radius-full', description: 'Dot border radius' },
    ],
  },
  {
    name: 'Chat',
    description: 'A chat conversation widget with message bubbles, auto-scroll, and a send interface.',
    category: 'composite',
    features: ['Message bubbles with user/other alignment', 'Auto-scroll to latest message', 'Keyboard submission via Enter', 'Timestamp display', 'Empty state with prompt'],
    variants: [],
    props: [
      { name: 'messages', type: 'ChatMessage[]', description: 'Array of chat messages to display' },
      { name: 'onSend', type: '(text: string) => void', description: 'Callback fired when the user sends a message' },
      { name: 'placeholder', type: 'string', default: 'Type a message...', description: 'Placeholder text for the message input' },
    ],
    cssVars: [
      { name: '--azimuth-color-primary', description: 'User message bubble background' },
      { name: '--azimuth-color-on-primary', description: 'User message text color' },
      { name: '--azimuth-color-surface', description: 'Other message bubble background' },
      { name: '--azimuth-color-border', description: 'Chat border colors' },
    ],
  },
  {
    name: 'Checkbox',
    description: 'A checkbox input component with label and indeterminate state support.',
    category: 'primitive',
    features: ['Label support via label prop or children', 'Indeterminate state for tri-state trees', 'Disabled state', 'Custom ID generation from label'],
    variants: [],
    props: [
      { name: 'label', type: 'string', description: 'The label text displayed next to the checkbox' },
      { name: 'indeterminate', type: 'boolean', default: 'false', description: 'Whether the checkbox is in an indeterminate state' },
      { name: 'disabled', type: 'boolean', description: 'Whether the checkbox is disabled' },
      { name: 'children', type: 'ReactNode', description: 'Alternative label content' },
    ],
    cssVars: [
      { name: '--azimuth-color-primary', description: 'Checked state color' },
      { name: '--azimuth-color-on-primary', description: 'Checkmark color' },
      { name: '--azimuth-color-surface', description: 'Unchecked background' },
    ],
  },
  {
    name: 'Chip',
    description: 'A compact element representing an input, filter, or selection with optional delete and avatar.',
    category: 'composite',
    features: ['Multiple color variants', 'Two sizes (sm, md)', 'Deletable with remove button', 'Selectable with click handler', 'Leading avatar/icon support'],
    variants: ['neutral', 'accent', 'success', 'warning', 'danger', 'info'],
    props: [
      { name: 'variant', type: 'string', default: 'neutral', description: 'The visual variant of the chip' },
      { name: 'size', type: 'string', default: 'md', description: 'The size of the chip' },
      { name: 'deletable', type: 'boolean', default: 'false', description: 'Whether the chip can be removed' },
      { name: 'onDelete', type: '() => void', description: 'Callback fired when the chip is deleted' },
      { name: 'selected', type: 'boolean', default: 'false', description: 'Whether the chip is selected' },
      { name: 'onClick', type: '() => void', description: 'Callback fired when the chip is clicked' },
      { name: 'avatar', type: 'ReactNode', description: 'Leading avatar or icon element' },
      { name: 'children', type: 'ReactNode', description: 'The content of the component' },
    ],
    cssVars: [
      { name: '--azimuth-radius-full', description: 'Chip border radius' },
      { name: '--azimuth-color-surface', description: 'Chip background' },
      { name: '--azimuth-color-text', description: 'Chip text color' },
    ],
  },
  {
    name: 'CodeBlock',
    description: 'A syntax-highlighted code display block with copy button and line numbers.',
    category: 'composite',
    features: ['Syntax highlighting with HTML output', 'Language label', 'Line number display', 'Copy to clipboard button', 'Max height with scroll', 'Toggleable highlighting'],
    variants: [],
    props: [
      { name: 'code', type: 'string', description: 'The source code string to display' },
      { name: 'language', type: 'string', description: 'The programming language for labeling' },
      { name: 'showLineNumbers', type: 'boolean', default: 'false', description: 'Whether to show line numbers' },
      { name: 'showCopyButton', type: 'boolean', default: 'false', description: 'Whether to show a copy button' },
      { name: 'maxHeight', type: 'string', description: 'Maximum height of the code block (CSS value)' },
      { name: 'highlight', type: 'boolean', default: 'true', description: 'Whether to apply syntax highlighting' },
    ],
    cssVars: [
      { name: '--azimuth-color-bg', description: 'Code block background' },
      { name: '--azimuth-font-mono', description: 'Code font family' },
      { name: '--azimuth-color-border', description: 'Code block border' },
    ],
  },
  {
    name: 'Container',
    description: 'A centered content container with max-width constraint.',
    category: 'layout',
    features: ['Centers content horizontally', 'Provides consistent max-width', 'Simple wrapper pattern'],
    variants: [],
    props: [
      { name: 'children', type: 'ReactNode', description: 'The content of the component' },
    ],
    cssVars: [
      { name: '--azimuth-space-xl', description: 'Container max-width' },
    ],
  },
  {
    name: 'DataTable',
    description: 'A feature-rich data table with sorting, searching, pagination, and editable rows.',
    category: 'composite',
    features: ['Column-based data display', 'Client-side and server-side sorting', 'Client-side and server-side search', 'Pagination with configurable page size', 'Editable rows', 'Loading and error states', 'Custom cell rendering'],
    variants: [],
    props: [
      { name: 'title', type: 'string', description: 'Optional title displayed above the table' },
      { name: 'columns', type: 'Column<T>[]', description: 'Column definitions for the table' },
      { name: 'data', type: 'T[]', description: 'Array of data rows' },
      { name: 'pageSize', type: 'number', description: 'Controlled page size for pagination' },
      { name: 'searchable', type: 'boolean', default: 'false', description: 'Whether to show the search input' },
      { name: 'loading', type: 'boolean', default: 'false', description: 'Whether data is loading' },
      { name: 'error', type: 'string', description: 'Error message string to display' },
      { name: 'editable', type: 'boolean', default: 'false', description: 'Whether rows have an edit action' },
      { name: 'onRowClick', type: '(row: T, index: number) => void', description: 'Callback fired when a row is clicked' },
    ],
    cssVars: [
      { name: '--azimuth-color-border', description: 'Table border color' },
      { name: '--azimuth-color-surface-hover', description: 'Row hover background' },
      { name: '--azimuth-color-text', description: 'Table text color' },
    ],
  },
  {
    name: 'DateRangePicker',
    description: 'A date range selector with start/end inputs and inline calendar popups.',
    category: 'composite',
    features: ['Start and end date selection', 'Inline calendar popups', 'Optional time selection', 'Min/max date constraints', 'Controlled or uncontrolled value'],
    variants: [],
    props: [
      { name: 'label', type: 'string', description: 'Label text for the picker' },
      { name: 'value', type: 'DateRange', description: 'Controlled date range value' },
      { name: 'onChange', type: '(range: DateRange) => void', description: 'Callback fired when the range changes' },
      { name: 'minDate', type: 'Date', description: 'Minimum selectable date' },
      { name: 'maxDate', type: 'Date', description: 'Maximum selectable date' },
      { name: 'includeTime', type: 'boolean', default: 'false', description: 'Whether to show time selection' },
      { name: 'placeholder', type: 'string', default: 'Select date', description: 'Placeholder text for inputs' },
    ],
    cssVars: [
      { name: '--azimuth-color-border', description: 'Input border color' },
      { name: '--azimuth-color-primary', description: 'Focus ring color' },
      { name: '--azimuth-color-surface', description: 'Popup background' },
    ],
  },
  {
    name: 'DateTimePicker',
    description: 'A combined date and time picker with a calendar and time selectors.',
    category: 'composite',
    features: ['Calendar date selection', 'Hour and minute selectors', 'Optional seconds selector', 'Configurable step sizes', 'Min/max date constraints', 'Controlled or uncontrolled value'],
    variants: [],
    props: [
      { name: 'value', type: 'Date', description: 'The controlled selected date/time' },
      { name: 'defaultValue', type: 'Date', description: 'The default selected date/time (uncontrolled)' },
      { name: 'onChange', type: '(date: Date) => void', description: 'Callback fired when the value changes' },
      { name: 'showTime', type: 'boolean', default: 'true', description: 'Whether to show time selection' },
      { name: 'showSeconds', type: 'boolean', default: 'false', description: 'Whether to show seconds selection' },
      { name: 'minDate', type: 'Date', description: 'Minimum selectable date' },
      { name: 'maxDate', type: 'Date', description: 'Maximum selectable date' },
    ],
    cssVars: [
      { name: '--azimuth-color-border', description: 'Picker border color' },
      { name: '--azimuth-color-surface', description: 'Picker background' },
      { name: '--azimuth-fs-sm', description: 'Label font size' },
    ],
  },
  {
    name: 'Dialog',
    description: 'A modal confirmation dialog with title, description, variant styling, and action buttons.',
    category: 'composite',
    features: ['Confirm and cancel actions', 'Info, warning, and danger variants', 'Escape key and backdrop click to close', 'Loading state with spinner', 'Focus trapping on open', 'Body scroll lock'],
    variants: ['info', 'warning', 'danger'],
    props: [
      { name: 'open', type: 'boolean', description: 'Whether the dialog is visible' },
      { name: 'onClose', type: '() => void', description: 'Callback fired when the dialog requests to close' },
      { name: 'title', type: 'string', description: 'Dialog title text' },
      { name: 'description', type: 'string', description: 'Dialog description text' },
      { name: 'variant', type: 'string', default: 'info', description: 'The visual variant of the dialog' },
      { name: 'confirmLabel', type: 'string', default: 'Confirm', description: 'Label for the confirm button' },
      { name: 'cancelLabel', type: 'string', default: 'Cancel', description: 'Label for the cancel button' },
      { name: 'onConfirm', type: '() => void', description: 'Callback fired when the confirm button is clicked' },
      { name: 'loading', type: 'boolean', default: 'false', description: 'Whether the dialog is in a loading state' },
    ],
    cssVars: [
      { name: '--azimuth-color-overlay', description: 'Backdrop overlay color' },
      { name: '--azimuth-color-surface', description: 'Dialog panel background' },
      { name: '--azimuth-color-text', description: 'Dialog text color' },
      { name: '--azimuth-color-primary', description: 'Confirm button background' },
    ],
  },
  {
    name: 'Divider',
    description: 'A horizontal or vertical separator line.',
    category: 'layout',
    features: ['Horizontal and vertical orientations', 'ARIA separator role', 'Thin visual border'],
    variants: ['horizontal', 'vertical'],
    props: [
      { name: 'orientation', type: 'string', default: 'horizontal', description: 'The orientation of the divider' },
    ],
    cssVars: [
      { name: '--azimuth-color-border', description: 'Divider line color' },
    ],
  },
  {
    name: 'Drawer',
    description: 'A slide-in panel from the left or right side of the screen.',
    category: 'composite',
    features: ['Left or right side sliding', 'Title and close button', 'Footer slot for actions', 'Escape key to close', 'Backdrop overlay', 'Persistent mode option', 'Body scroll lock'],
    variants: ['sm', 'md', 'lg'],
    props: [
      { name: 'open', type: 'boolean', description: 'Whether the drawer is visible' },
      { name: 'onClose', type: '() => void', description: 'Callback fired when the drawer requests to close' },
      { name: 'side', type: 'string', default: 'left', description: 'The side of the screen the drawer slides from' },
      { name: 'title', type: 'string', description: 'Drawer title text' },
      { name: 'size', type: 'string', default: 'md', description: 'The width of the drawer' },
      { name: 'persistent', type: 'boolean', default: 'false', description: 'Whether clicking the overlay closes the drawer' },
      { name: 'children', type: 'ReactNode', description: 'The content of the drawer body' },
      { name: 'footer', type: 'ReactNode', description: 'Footer content' },
    ],
    cssVars: [
      { name: '--azimuth-color-overlay', description: 'Backdrop overlay color' },
      { name: '--azimuth-color-surface', description: 'Drawer panel background' },
      { name: '--azimuth-shadow-lg', description: 'Drawer shadow' },
      { name: '--azimuth-color-border', description: 'Drawer border' },
    ],
  },
  {
    name: 'DropdownList',
    description: 'A dropdown select component with search, multiple selection, and keyboard navigation.',
    category: 'composite',
    features: ['Single and multiple selection modes', 'Search/filter built-in', 'Keyboard navigation', 'Option separators', 'Error state display', 'Disabled options', 'Click-outside to close'],
    variants: [],
    props: [
      { name: 'label', type: 'string', description: 'The label text for the dropdown' },
      { name: 'options', type: 'Array<{ value: string; label: string; disabled?: boolean }>', description: 'Array of dropdown options' },
      { name: 'value', type: 'string | string[]', description: 'Controlled selected value(s)' },
      { name: 'onChange', type: '(value: string | string[]) => void', description: 'Callback fired when selection changes' },
      { name: 'placeholder', type: 'string', default: 'Select...', description: 'Placeholder text when nothing is selected' },
      { name: 'multiple', type: 'boolean', default: 'false', description: 'Whether multiple selections are allowed' },
      { name: 'searchable', type: 'boolean', default: 'false', description: 'Whether to show a search input' },
      { name: 'disabled', type: 'boolean', default: 'false', description: 'Whether the dropdown is disabled' },
      { name: 'error', type: 'string', description: 'Error message to display' },
    ],
    cssVars: [
      { name: '--azimuth-color-border', description: 'Dropdown border color' },
      { name: '--azimuth-color-surface', description: 'Dropdown background' },
      { name: '--azimuth-color-text', description: 'Dropdown text color' },
      { name: '--azimuth-shadow-md', description: 'Panel shadow' },
    ],
  },
  {
    name: 'EmptyState',
    description: 'An empty state placeholder with icon, title, description, and optional action.',
    category: 'composite',
    features: ['Icon slot above title', 'Title and description text', 'Action slot for call-to-action', 'Centered vertical layout'],
    variants: [],
    props: [
      { name: 'icon', type: 'ReactNode', description: 'Optional icon rendered above the title' },
      { name: 'title', type: 'string', description: 'The title text' },
      { name: 'description', type: 'string', description: 'An optional description below the title' },
      { name: 'action', type: 'ReactNode', description: 'Action element rendered at the bottom' },
    ],
    cssVars: [
      { name: '--azimuth-color-text', description: 'Title text color' },
      { name: '--azimuth-color-text-muted', description: 'Description text color' },
    ],
  },
  {
    name: 'FanMenu',
    description: 'An expandable radial menu that fans out options in a chosen direction.',
    category: 'composite',
    features: ['Animated expansion with staggered delays', 'Four expansion directions (up, down, left, right)', 'Custom trigger element', 'Configurable gap between options', 'Keyboard accessible', 'Click-outside to close'],
    variants: [],
    props: [
      { name: 'options', type: 'FanMenuOption[]', description: 'Array of fan menu options' },
      { name: 'trigger', type: 'ReactNode', description: 'Custom trigger element' },
      { name: 'direction', type: 'string', default: 'up', description: 'Direction the menu expands' },
      { name: 'gap', type: 'number', default: '8', description: 'Spacing between options in pixels' },
    ],
    cssVars: [
      { name: '--azimuth-color-primary', description: 'Trigger button color' },
      { name: '--azimuth-color-surface', description: 'Option background' },
      { name: '--azimuth-shadow-md', description: 'Option shadow' },
    ],
  },
  {
    name: 'FileUpload',
    description: 'A drag-and-drop file upload area with click-to-browse and paste support.',
    category: 'composite',
    features: ['Drag and drop with visual feedback', 'Click to open native file browser', 'Paste images from clipboard', 'File size validation', 'File list with remove buttons', 'Keyboard accessible'],
    variants: [],
    props: [
      { name: 'onFilesSelected', type: '(files: File[]) => void', description: 'Callback fired when files are selected, dropped, or pasted' },
      { name: 'accept', type: 'string', description: 'Accepted file types string' },
      { name: 'multiple', type: 'boolean', default: 'true', description: 'Whether multiple files can be selected' },
      { name: 'maxSize', type: 'number', default: '10', description: 'Maximum file size in megabytes' },
      { name: 'disabled', type: 'boolean', default: 'false', description: 'Whether the upload area is disabled' },
    ],
    cssVars: [
      { name: '--azimuth-color-border', description: 'Drop zone border color' },
      { name: '--azimuth-color-accent', description: 'Drag-over accent color' },
      { name: '--azimuth-color-surface', description: 'Upload area background' },
    ],
  },
  {
    name: 'Flyout',
    description: 'A hover-triggered popover with configurable delay and positioning.',
    category: 'composite',
    features: ['Hover/focus trigger with configurable delays', 'Four placement sides (top, bottom, left, right)', 'Keyboard accessible via Enter/Escape', 'Auto-cleanup of timers'],
    variants: [],
    props: [
      { name: 'trigger', type: 'ReactNode', description: 'The element that triggers the flyout' },
      { name: 'content', type: 'ReactNode', description: 'The content rendered inside the flyout' },
      { name: 'side', type: 'string', default: 'bottom', description: 'Placement of the flyout relative to the trigger' },
      { name: 'openDelay', type: 'number', default: '200', description: 'Delay before opening in milliseconds' },
      { name: 'closeDelay', type: 'number', default: '150', description: 'Delay before closing in milliseconds' },
    ],
    cssVars: [
      { name: '--azimuth-color-surface', description: 'Flyout background' },
      { name: '--azimuth-shadow-md', description: 'Flyout shadow' },
      { name: '--azimuth-color-border', description: 'Flyout border' },
    ],
  },
  {
    name: 'Form',
    description: 'A form wrapper with automatic form data collection and field components.',
    category: 'composite',
    features: ['Form data collection via FormData API', 'Field subcomponent with label, error, and help text', 'Required field indication', 'Configurable vertical spacing', 'No-validate by default'],
    variants: [],
    props: [
      { name: 'onSubmit', type: '(data: Record<string, FormDataEntryValue>) => void', description: 'Callback fired with form data keyed by field name' },
      { name: 'spacing', type: 'string', default: 'md', description: 'Vertical spacing between fields' },
      { name: 'children', type: 'ReactNode', description: 'The content of the component' },
    ],
    cssVars: [
      { name: '--azimuth-space-md', description: 'Field spacing' },
      { name: '--azimuth-color-error-text', description: 'Error text color' },
      { name: '--azimuth-fs-sm', description: 'Label font size' },
    ],
  },
  {
    name: 'Grid',
    description: 'A CSS Grid layout component with configurable columns, gap, and alignment.',
    category: 'layout',
    features: ['Configurable column count (1-4 or auto-fit)', 'CSS gap via spacing tokens', 'Item alignment options', 'Auto, highlight, and sidebar variants', 'Responsive by default'],
    variants: ['auto', 'highlight', 'sidebar'],
    props: [
      { name: 'cols', type: 'number | string', default: 'auto', description: 'The number of columns or auto-fit behavior' },
      { name: 'gap', type: 'string', description: 'The spacing token for grid gap' },
      { name: 'align', type: 'string', description: 'Vertical alignment of grid items' },
      { name: 'variant', type: 'string', default: 'auto', description: 'The visual variant of the grid' },
      { name: 'children', type: 'ReactNode', description: 'The content of the component' },
    ],
    cssVars: [
      { name: '--azimuth-space-lg', description: 'Default grid gap' },
    ],
  },
  {
    name: 'Icon',
    description: 'A wrapper component for rendering icons with consistent sizing.',
    category: 'primitive',
    features: ['Consistent sizing via size prop', 'Five size options (sm, md, lg, xl, xl2)', 'Aria-hidden by default for decorative icons'],
    variants: ['sm', 'md', 'lg', 'xl', 'xl2'],
    props: [
      { name: 'size', type: 'string', default: 'md', description: 'The size of the icon' },
      { name: 'children', type: 'ReactNode', description: 'The icon element to render' },
    ],
    cssVars: [],
  },
  {
    name: 'Input',
    description: 'A text input component with label, validation, autocomplete, and stepper support.',
    category: 'primitive',
    features: ['Label with top/left/inner positioning', 'Helper subtitle text', 'Error message display', 'Autocomplete suggestions dropdown', 'Number stepper buttons', 'Character count with max length'],
    variants: [],
    props: [
      { name: 'label', type: 'string', description: 'The label text for the input' },
      { name: 'subtitle', type: 'string', description: 'Helper text displayed below the label' },
      { name: 'error', type: 'string', description: 'Error message displayed below the input' },
      { name: 'required', type: 'boolean', default: 'false', description: 'Whether the input is required' },
      { name: 'size', type: 'string', default: 'md', description: 'The size of the input' },
      { name: 'labelPosition', type: 'string', default: 'top', description: 'The position of the label relative to the input' },
      { name: 'showSteppers', type: 'boolean', default: 'false', description: 'Whether to show increment/decrement steppers for number inputs' },
      { name: 'autocompleteOptions', type: 'string[]', description: 'List of autocomplete suggestions' },
    ],
    cssVars: [
      { name: '--azimuth-color-border', description: 'Input border color' },
      { name: '--azimuth-color-primary', description: 'Focus ring color' },
      { name: '--azimuth-color-surface', description: 'Input background' },
      { name: '--azimuth-color-text', description: 'Input text color' },
    ],
  },
  {
    name: 'InputGroup',
    description: 'A layout wrapper that groups related form inputs together.',
    category: 'composite',
    features: ['Groups inputs without visual separation', 'ARIA group role for accessibility', 'Simple wrapper pattern'],
    variants: [],
    props: [
      { name: 'children', type: 'ReactNode', description: 'The content of the component' },
    ],
    cssVars: [
      { name: '--azimuth-radius', description: 'Input group border radius' },
    ],
  },
  {
    name: 'Kbd',
    description: 'A keyboard shortcut indicator styled as a inline keycap element.',
    category: 'composite',
    features: ['Inline keyboard shortcut styling', 'Monospace font', 'Subtle bordered appearance'],
    variants: [],
    props: [
      { name: 'children', type: 'ReactNode', description: 'The keyboard shortcut text' },
    ],
    cssVars: [
      { name: '--azimuth-color-surface', description: 'Keycap background' },
      { name: '--azimuth-color-border', description: 'Keycap border' },
      { name: '--azimuth-font-mono', description: 'Keycap font' },
    ],
  },
  {
    name: 'List',
    description: 'An ordered or unordered list with configurable spacing and bullet markers.',
    category: 'composite',
    features: ['Ordered (ol) or unordered (ul) display', 'Configurable spacing between items', 'Bullet marker toggle', 'Item subcomponent'],
    variants: [],
    props: [
      { name: 'ordered', type: 'boolean', default: 'false', description: 'Whether to render an ordered list' },
      { name: 'spacing', type: 'string', default: 'md', description: 'Spacing between list items' },
      { name: 'bulleted', type: 'boolean', default: 'false', description: 'Whether to show bullet markers' },
      { name: 'children', type: 'ReactNode', description: 'The content of the component' },
    ],
    cssVars: [
      { name: '--azimuth-color-text', description: 'List text color' },
      { name: '--azimuth-fs-sm', description: 'List font size' },
    ],
  },
  {
    name: 'Loader',
    description: 'A loading indicator with circular spinner or horizontal bar variants.',
    category: 'composite',
    features: ['Circle spinner and bar progress variants', 'Three sizes (sm, md, lg)', 'Accessible label with status role', 'Custom label text'],
    variants: ['circle', 'bar'],
    props: [
      { name: 'variant', type: 'string', default: 'circle', description: 'The visual variant of the loader' },
      { name: 'size', type: 'string', default: 'md', description: 'The size of the loader' },
      { name: 'label', type: 'string', description: 'Accessible label for the loader' },
    ],
    cssVars: [
      { name: '--azimuth-color-primary', description: 'Spinner/bar accent color' },
      { name: '--azimuth-fs-sm', description: 'Label font size' },
    ],
  },
  {
    name: 'LoginSignup',
    description: 'A complete authentication form with login, signup, and password reset views.',
    category: 'composite',
    features: ['Login, signup, and password reset tabs', 'External OAuth provider buttons', 'Remember me checkbox', 'Loading state with spinner', 'Error message display', 'Forgot password flow'],
    variants: [],
    props: [
      { name: 'defaultView', type: 'string', default: 'login', description: 'The initial view to display' },
      { name: 'providers', type: 'AuthProvider[]', description: 'Array of external auth providers' },
      { name: 'onLogin', type: '(data: { email: string; password: string }) => void', description: 'Callback fired on login submit' },
      { name: 'onSignup', type: '(data: { name?: string; email: string; password: string }) => void', description: 'Callback fired on signup submit' },
      { name: 'onResetPassword', type: '(data: { email: string }) => void', description: 'Callback fired on password reset submit' },
      { name: 'onProviderAuth', type: '(providerId: string) => void', description: 'Callback fired when an external provider is clicked' },
      { name: 'loading', type: 'boolean', default: 'false', description: 'Whether the form is submitting' },
      { name: 'error', type: 'string', description: 'Error message to display' },
    ],
    cssVars: [
      { name: '--azimuth-color-primary', description: 'Submit button and active tab color' },
      { name: '--azimuth-color-surface', description: 'Form background' },
      { name: '--azimuth-color-border', description: 'Input border colors' },
    ],
  },
  {
    name: 'Menu',
    description: 'A dropdown menu with keyboard navigation, icons, and destructive action styling.',
    category: 'composite',
    features: ['Custom trigger element', 'Keyboard navigation with arrow keys', 'Item icons and danger styling', 'Separator support', 'Click-outside to close'],
    variants: [],
    props: [
      { name: 'items', type: 'MenuItem[]', description: 'Array of menu items' },
      { name: 'trigger', type: 'ReactNode', description: 'Custom trigger element' },
      { name: 'onSelect', type: '(key: string) => void', description: 'Callback fired when an item is selected' },
      { name: 'side', type: 'string', default: 'left', description: 'Horizontal alignment of the dropdown' },
    ],
    cssVars: [
      { name: '--azimuth-color-surface', description: 'Menu background' },
      { name: '--azimuth-shadow-md', description: 'Menu shadow' },
      { name: '--azimuth-color-border', description: 'Menu border' },
    ],
  },
  {
    name: 'Modal',
    description: 'A centered modal dialog with backdrop, title, subtitle, and footer slots.',
    category: 'composite',
    features: ['Centered overlay modal', 'Title, subtitle, and footer slots', 'Backdrop blur options', 'Multiple sizes (sm to full)', 'Escape key and backdrop click to close', 'Persistent mode option', 'Body scroll lock'],
    variants: ['sm', 'md', 'lg', 'xl', 'full'],
    props: [
      { name: 'open', type: 'boolean', description: 'Whether the modal is visible' },
      { name: 'onClose', type: '() => void', description: 'Callback fired when the modal requests to close' },
      { name: 'title', type: 'string', description: 'Modal title text' },
      { name: 'subtitle', type: 'string', description: 'Optional subtitle text' },
      { name: 'persistent', type: 'boolean', default: 'false', description: 'Whether clicking the overlay closes the modal' },
      { name: 'blur', type: 'string', default: 'none', description: 'Backdrop blur intensity' },
      { name: 'size', type: 'string', default: 'md', description: 'The size of the modal' },
      { name: 'footer', type: 'ReactNode', description: 'Footer content' },
      { name: 'children', type: 'ReactNode', description: 'The content of the modal body' },
    ],
    cssVars: [
      { name: '--azimuth-color-overlay', description: 'Backdrop overlay color' },
      { name: '--azimuth-color-surface', description: 'Modal panel background' },
      { name: '--azimuth-shadow-lg', description: 'Modal shadow' },
      { name: '--azimuth-color-border', description: 'Modal border' },
    ],
  },
  {
    name: 'Navbar',
    description: 'A responsive navigation bar with logo, links, actions, and mobile drawer.',
    category: 'composite',
    features: ['Logo with link', 'Navigation items with active state', 'Action slot on the right', 'Responsive mobile hamburger menu', 'Slide-in mobile drawer with overlay', 'Configurable mobile breakpoint'],
    variants: [],
    props: [
      { name: 'logo', type: 'ReactNode', description: 'Branding element displayed on the left' },
      { name: 'logoHref', type: 'string', default: '/', description: 'URL the logo links to' },
      { name: 'items', type: 'NavItem[]', description: 'Navigation items to render' },
      { name: 'activeKey', type: 'string', description: 'Key of the currently active nav item' },
      { name: 'actions', type: 'ReactNode', description: 'Action elements displayed on the right side' },
      { name: 'mobileBreakpoint', type: 'number', default: '768', description: 'Viewport width in pixels below which the mobile menu activates' },
    ],
    cssVars: [
      { name: '--azimuth-color-surface', description: 'Navbar background' },
      { name: '--azimuth-color-text', description: 'Navbar text color' },
      { name: '--azimuth-color-primary', description: 'Active link color' },
    ],
  },
  {
    name: 'PageLayout',
    description: 'A full-page layout shell with top nav, sidebar, main content, and footer zones.',
    category: 'composite',
    features: ['Top navigation bar slot', 'Sidebar with configurable width and position', 'Main content area', 'Footer slot', 'Custom sidebar width via CSS variable'],
    variants: [],
    props: [
      { name: 'sidebar', type: 'ReactNode', description: 'Sidebar content to render beside the main content' },
      { name: 'sidebarWidth', type: 'string', default: '260px', description: 'Width of the sidebar as a CSS value' },
      { name: 'sidebarPosition', type: 'string', default: 'left', description: 'Position of the sidebar relative to the content' },
      { name: 'topNav', type: 'ReactNode', description: 'Top navigation bar content' },
      { name: 'footer', type: 'ReactNode', description: 'Footer content rendered at the bottom of the layout' },
      { name: 'children', type: 'ReactNode', description: 'The content of the component' },
    ],
    cssVars: [
      { name: '--azimuth-color-bg', description: 'Page background' },
      { name: '--azimuth-color-surface', description: 'Sidebar background' },
      { name: '--azimuth-color-border', description: 'Sidebar border' },
    ],
  },
  {
    name: 'Pagination',
    description: 'A page navigation control with ellipsis collapsing and optional first/last buttons.',
    category: 'composite',
    features: ['Page range with sibling count', 'Ellipsis collapsing for large page counts', 'First/last page buttons (optional)', 'Previous/next navigation', 'Current page highlight', 'Two size variants'],
    variants: ['sm', 'md'],
    props: [
      { name: 'currentPage', type: 'number', description: 'The currently active page number (1-based)' },
      { name: 'totalPages', type: 'number', description: 'Total number of pages' },
      { name: 'onPageChange', type: '(page: number) => void', description: 'Callback fired when a page is selected' },
      { name: 'siblingCount', type: 'number', default: '1', description: 'Number of sibling pages shown on each side of the current page' },
      { name: 'showFirstLast', type: 'boolean', default: 'false', description: 'Whether to show first/last page buttons' },
      { name: 'size', type: 'string', default: 'md', description: 'Size variant of the pagination component' },
    ],
    cssVars: [
      { name: '--azimuth-color-primary', description: 'Active page background' },
      { name: '--azimuth-color-on-primary', description: 'Active page text color' },
      { name: '--azimuth-color-surface', description: 'Page button background' },
      { name: '--azimuth-color-border', description: 'Button border color' },
    ],
  },
  {
    name: 'ProgressBar',
    description: 'A progress indicator bar with determinate and indeterminate modes.',
    category: 'composite',
    features: ['Determinate and indeterminate modes', 'Five color variants', 'Three size variants', 'ARIA progressbar role with value/text'],
    variants: ['primary', 'accent', 'success', 'warning', 'danger'],
    props: [
      { name: 'value', type: 'number', default: '0', description: 'The current progress value' },
      { name: 'max', type: 'number', default: '100', description: 'The maximum progress value' },
      { name: 'indeterminate', type: 'boolean', default: 'false', description: 'Whether the progress bar is in indeterminate mode' },
      { name: 'color', type: 'string', default: 'primary', description: 'Color variant of the progress bar' },
      { name: 'size', type: 'string', default: 'md', description: 'Size variant of the progress bar' },
    ],
    cssVars: [
      { name: '--azimuth-color-primary', description: 'Primary progress fill color' },
      { name: '--azimuth-radius-full', description: 'Progress bar border radius' },
    ],
  },
  {
    name: 'Radio',
    description: 'A radio button input component with label support.',
    category: 'primitive',
    features: ['Label support via label prop or children', 'Disabled state', 'Custom ID generation from label'],
    variants: [],
    props: [
      { name: 'label', type: 'string', description: 'The label text displayed next to the radio button' },
      { name: 'disabled', type: 'boolean', description: 'Whether the radio is disabled' },
      { name: 'children', type: 'ReactNode', description: 'Alternative label content' },
    ],
    cssVars: [
      { name: '--azimuth-color-primary', description: 'Checked state color' },
      { name: '--azimuth-color-surface', description: 'Unchecked background' },
      { name: '--azimuth-color-text', description: 'Label text color' },
    ],
  },
  {
    name: 'ResizablePanel',
    description: 'A split panel layout with draggable dividers for resizing child panels.',
    category: 'composite',
    features: ['Horizontal and vertical splitting', 'Draggable dividers with keyboard support', 'Configurable initial sizes', 'Minimum size enforcement', 'Drag overlay cursor'],
    variants: [],
    props: [
      { name: 'direction', type: 'string', default: 'horizontal', description: 'Direction in which panels can be resized' },
      { name: 'defaultSizes', type: 'number[]', description: 'Initial size distribution for child panels as percentages' },
      { name: 'minSize', type: 'number', default: '50', description: 'Minimum size in pixels for each panel' },
      { name: 'children', type: 'ReactNode', description: 'The content of the component' },
    ],
    cssVars: [
      { name: '--azimuth-color-border', description: 'Divider color' },
      { name: '--azimuth-color-primary', description: 'Active divider color' },
    ],
  },
  {
    name: 'SearchBar',
    description: 'A search input with debounced search, suggestions dropdown, and clear button.',
    category: 'composite',
    features: ['Debounced search callback', 'Suggestions dropdown with keyboard navigation', 'Clearable input', 'Controlled or uncontrolled value', 'Search role for accessibility'],
    variants: [],
    props: [
      { name: 'onSearch', type: '(query: string) => void', description: 'Callback fired with the debounced search query' },
      { name: 'suggestions', type: 'string[]', description: 'Array of suggestion strings to display as the user types' },
      { name: 'onSuggestionSelect', type: '(suggestion: string) => void', description: 'Callback fired when a suggestion is selected' },
      { name: 'debounceMs', type: 'number', default: '300', description: 'Debounce delay in milliseconds before firing onSearch' },
      { name: 'placeholder', type: 'string', default: 'Search...', description: 'Placeholder text for the search input' },
      { name: 'clearable', type: 'boolean', default: 'true', description: 'Whether to show a clear button when the input has a value' },
    ],
    cssVars: [
      { name: '--azimuth-color-border', description: 'Search bar border color' },
      { name: '--azimuth-color-surface', description: 'Search bar background' },
      { name: '--azimuth-fs-base', description: 'Input font size' },
    ],
  },
  {
    name: 'SectionView',
    description: 'A collapsible section with a toggleable header and animated content reveal.',
    category: 'composite',
    features: ['Collapsible with chevron animation', 'Controlled or uncontrolled expansion', 'ARIA region with labelledby', 'Unique IDs for accessibility'],
    variants: [],
    props: [
      { name: 'title', type: 'string', description: 'Title text displayed in the section header' },
      { name: 'defaultExpanded', type: 'boolean', default: 'false', description: 'Whether the section is expanded by default' },
      { name: 'expanded', type: 'boolean', description: 'Whether the section is expanded (controlled)' },
      { name: 'onToggle', type: '(expanded: boolean) => void', description: 'Callback fired when the expanded state changes' },
      { name: 'children', type: 'ReactNode', description: 'The content of the component' },
    ],
    cssVars: [
      { name: '--azimuth-color-border', description: 'Section border color' },
      { name: '--azimuth-color-surface', description: 'Section background' },
      { name: '--azimuth-color-text', description: 'Section title color' },
    ],
  },
  {
    name: 'SegmentedButton',
    description: 'A segmented control group for mutually exclusive options with keyboard navigation.',
    category: 'composite',
    features: ['Mutually exclusive selection (radio group)', 'Keyboard navigation with arrow keys', 'Icons in options', 'Three sizes (sm, md, lg)', 'Full width option'],
    variants: [],
    props: [
      { name: 'options', type: 'SegmentedButtonOption[]', description: 'Array of options to render' },
      { name: 'value', type: 'string', description: 'Currently selected value (controlled)' },
      { name: 'defaultValue', type: 'string', description: 'Default selected value (uncontrolled)' },
      { name: 'onChange', type: '(value: string) => void', description: 'Callback fired when the selected value changes' },
      { name: 'size', type: 'string', default: 'md', description: 'Size variant of the segmented button' },
      { name: 'fullWidth', type: 'boolean', default: 'false', description: 'Whether the button group stretches to full width' },
    ],
    cssVars: [
      { name: '--azimuth-color-primary', description: 'Selected option background' },
      { name: '--azimuth-color-on-primary', description: 'Selected option text color' },
      { name: '--azimuth-color-border', description: 'Segmented button border' },
    ],
  },
  {
    name: 'Select',
    description: 'A select dropdown component with label, validation, and custom options.',
    category: 'primitive',
    features: ['Native select element', 'Label with required indicator', 'Helper subtitle text', 'Error message display', 'Placeholder option', 'Three sizes'],
    variants: [],
    props: [
      { name: 'label', type: 'string', description: 'The label text for the select' },
      { name: 'subtitle', type: 'string', description: 'Helper text displayed below the label' },
      { name: 'error', type: 'string', description: 'Error message displayed below the select' },
      { name: 'required', type: 'boolean', default: 'false', description: 'Whether the select is required' },
      { name: 'size', type: 'string', default: 'md', description: 'The size of the select' },
      { name: 'placeholder', type: 'string', description: 'Placeholder option text' },
      { name: 'options', type: 'Array<{ value: string; label: string; disabled?: boolean }>', description: 'The list of options to display' },
    ],
    cssVars: [
      { name: '--azimuth-color-border', description: 'Select border color' },
      { name: '--azimuth-color-surface', description: 'Select background' },
      { name: '--azimuth-color-text', description: 'Select text color' },
    ],
  },
  {
    name: 'Skeleton',
    description: 'A loading placeholder component with text, circle, and rectangle variants.',
    category: 'composite',
    features: ['Text, circle, and rectangle shapes', 'Custom width and height', 'Multiple items via count prop', 'Animated shimmer effect', 'Accessible loading status'],
    variants: ['text', 'circle', 'rect'],
    props: [
      { name: 'variant', type: 'string', default: 'text', description: 'Shape variant of the skeleton placeholder' },
      { name: 'width', type: 'string', description: 'Width of the skeleton as a CSS value' },
      { name: 'height', type: 'string', description: 'Height of the skeleton as a CSS value' },
      { name: 'count', type: 'number', default: '1', description: 'Number of skeleton items to render' },
    ],
    cssVars: [
      { name: '--azimuth-color-border', description: 'Skeleton background color' },
      { name: '--azimuth-radius', description: 'Skeleton border radius' },
    ],
  },
  {
    name: 'Slider',
    description: 'A range slider input with horizontal/vertical orientation and value display.',
    category: 'composite',
    features: ['Horizontal and vertical orientations', 'Controlled or uncontrolled value', 'Value label display', 'Keyboard navigation', 'Pointer drag support', 'Three size variants'],
    variants: [],
    props: [
      { name: 'min', type: 'number', default: '0', description: 'Minimum value of the slider' },
      { name: 'max', type: 'number', default: '100', description: 'Maximum value of the slider' },
      { name: 'step', type: 'number', default: '1', description: 'Step increment for the slider' },
      { name: 'value', type: 'number', description: 'Current slider value (controlled)' },
      { name: 'defaultValue', type: 'number', description: 'Default slider value (uncontrolled)' },
      { name: 'onChange', type: '(value: number) => void', description: 'Callback fired when the slider value changes' },
      { name: 'orientation', type: 'string', default: 'horizontal', description: 'Orientation of the slider' },
      { name: 'showValue', type: 'boolean', default: 'false', description: 'Whether to display the current value as a label' },
    ],
    cssVars: [
      { name: '--azimuth-color-primary', description: 'Slider fill and thumb color' },
      { name: '--azimuth-color-surface', description: 'Track background' },
      { name: '--azimuth-radius-full', description: 'Thumb border radius' },
    ],
  },
  {
    name: 'SlideSheet',
    description: 'A slide-in panel from any side of the screen with configurable size and snap points.',
    category: 'composite',
    features: ['Four slide directions (top, bottom, left, right)', 'Configurable height/width', 'Snap point support', 'Title and close button', 'Escape key and backdrop click to close', 'Body scroll lock', 'Drag handle on bottom sheets'],
    variants: [],
    props: [
      { name: 'open', type: 'boolean', description: 'Whether the sheet is open' },
      { name: 'onClose', type: '() => void', description: 'Callback fired when the sheet requests to close' },
      { name: 'side', type: 'string', default: 'bottom', description: 'Side of the screen from which the sheet slides in' },
      { name: 'title', type: 'string', description: 'Title displayed in the sheet header' },
      { name: 'height', type: 'string', description: 'Height or width of the sheet as a CSS value' },
      { name: 'snapPoints', type: 'string[]', description: 'Array of snap point sizes as CSS values' },
      { name: 'persistent', type: 'boolean', default: 'false', description: 'Whether clicking the overlay should close the sheet' },
      { name: 'children', type: 'ReactNode', description: 'The content of the component' },
    ],
    cssVars: [
      { name: '--azimuth-color-surface', description: 'Sheet background' },
      { name: '--azimuth-color-overlay', description: 'Backdrop overlay color' },
      { name: '--azimuth-shadow-lg', description: 'Sheet shadow' },
    ],
  },
  {
    name: 'Stack',
    description: 'A flexbox layout component for stacking elements with configurable direction and spacing.',
    category: 'layout',
    features: ['Horizontal and vertical stacking', 'Cross-axis alignment', 'Main-axis distribution (justify)', 'Six spacing token levels', 'Wrap support'],
    variants: [],
    props: [
      { name: 'direction', type: 'string', default: 'vertical', description: 'The direction to stack elements' },
      { name: 'align', type: 'string', description: 'Cross-axis alignment of stack items' },
      { name: 'justify', type: 'string', description: 'Main-axis distribution of stack items' },
      { name: 'spacing', type: 'string', default: 'md', description: 'The spacing between stack items' },
      { name: 'wrap', type: 'boolean', default: 'false', description: 'Whether stack items should wrap to the next line' },
      { name: 'children', type: 'ReactNode', description: 'The content of the component' },
    ],
    cssVars: [
      { name: '--azimuth-space-xs', description: 'Extra small gap' },
      { name: '--azimuth-space-sm', description: 'Small gap' },
      { name: '--azimuth-space-md', description: 'Medium gap' },
      { name: '--azimuth-space-lg', description: 'Large gap' },
      { name: '--azimuth-space-xl', description: 'Extra large gap' },
      { name: '--azimuth-space-2xl', description: '2x extra large gap' },
    ],
  },
  {
    name: 'Table',
    description: 'A styled HTML table component with striped, bordered, and hoverable variants.',
    category: 'composite',
    features: ['Striped alternating rows', 'Visible borders', 'Hover row highlighting', 'Two size variants', 'Subcomponents: Head, Body, Row, Cell, HeadCell'],
    variants: [],
    props: [
      { name: 'striped', type: 'boolean', default: 'false', description: 'Whether rows have alternating background colors' },
      { name: 'bordered', type: 'boolean', default: 'false', description: 'Whether the table has visible borders' },
      { name: 'hoverable', type: 'boolean', default: 'false', description: 'Whether rows are highlighted on hover' },
      { name: 'size', type: 'string', default: 'md', description: 'Size variant of the table' },
      { name: 'children', type: 'ReactNode', description: 'The content of the component' },
    ],
    cssVars: [
      { name: '--azimuth-color-border', description: 'Table border color' },
      { name: '--azimuth-color-surface', description: 'Table background' },
      { name: '--azimuth-color-surface-hover', description: 'Hover row background' },
    ],
  },
  {
    name: 'Tabs',
    description: 'A tabbed content switcher with underline, pills, and button variants.',
    category: 'composite',
    features: ['Three tab variants (underline, pills, buttons)', 'Keyboard navigation with arrow keys', 'Disabled tab support', 'Controlled or uncontrolled active tab', 'ARIA tab pattern with roving tabindex'],
    variants: ['underline', 'pills', 'buttons'],
    props: [
      { name: 'tabs', type: 'Array<{ id: string; label: string; content: ReactNode; disabled?: boolean }>', description: 'Array of tab items to render' },
      { name: 'defaultTab', type: 'string', description: 'ID of the default active tab (uncontrolled)' },
      { name: 'activeTab', type: 'string', description: 'ID of the currently active tab (controlled)' },
      { name: 'onChange', type: '(tabId: string) => void', description: 'Callback fired when the active tab changes' },
      { name: 'variant', type: 'string', default: 'underline', description: 'Visual variant of the tab control' },
    ],
    cssVars: [
      { name: '--azimuth-color-primary', description: 'Active tab indicator color' },
      { name: '--azimuth-color-primary-subtle', description: 'Pills active background' },
      { name: '--azimuth-color-text', description: 'Tab text color' },
    ],
  },
  {
    name: 'Tag',
    description: 'A small label tag with color variants and optional remove button.',
    category: 'composite',
    features: ['Six color variants', 'Optional remove button', 'Compact inline display'],
    variants: ['neutral', 'accent', 'success', 'warning', 'danger', 'info'],
    props: [
      { name: 'variant', type: 'string', default: 'neutral', description: 'Color variant of the tag' },
      { name: 'removable', type: 'boolean', default: 'false', description: 'Whether the tag displays a remove button' },
      { name: 'onRemove', type: '() => void', description: 'Callback fired when the remove button is clicked' },
      { name: 'children', type: 'ReactNode', description: 'The content of the component' },
    ],
    cssVars: [
      { name: '--azimuth-radius-sm', description: 'Tag border radius' },
      { name: '--azimuth-fs-xs', description: 'Tag font size' },
    ],
  },
  {
    name: 'Text',
    description: 'A typography component with size, weight, color, and variant options.',
    category: 'primitive',
    features: ['Multiple font sizes from xs to h1', 'Font weight options', 'Text color variants', 'Typography variants (display, heading, body, mono)', 'Uppercase, truncate, and nowrap utilities', 'Custom HTML element via as prop'],
    variants: ['display', 'heading', 'body', 'mono'],
    props: [
      { name: 'as', type: 'ElementType', description: 'The HTML element or component to render as' },
      { name: 'size', type: 'string', default: 'base', description: 'The font size' },
      { name: 'weight', type: 'string', description: 'The font weight' },
      { name: 'color', type: 'string', description: 'The text color' },
      { name: 'variant', type: 'string', default: 'body', description: 'The typographic style variant' },
      { name: 'uppercase', type: 'boolean', default: 'false', description: 'Whether to transform text to uppercase' },
      { name: 'truncate', type: 'boolean', default: 'false', description: 'Whether to truncate text with an ellipsis' },
      { name: 'children', type: 'ReactNode', description: 'The content of the component' },
    ],
    cssVars: [
      { name: '--azimuth-font-body', description: 'Body font family' },
      { name: '--azimuth-font-display', description: 'Display font family' },
      { name: '--azimuth-font-mono', description: 'Monospace font family' },
      { name: '--azimuth-color-text', description: 'Default text color' },
      { name: '--azimuth-color-text-secondary', description: 'Secondary text color' },
    ],
  },
  {
    name: 'TextArea',
    description: 'A multi-line text input with label, validation, and character count.',
    category: 'composite',
    features: ['Label with character count', 'Helper subtitle text', 'Error message display', 'Max length enforcement', 'Three size variants'],
    variants: [],
    props: [
      { name: 'label', type: 'string', description: 'Label text displayed above the textarea' },
      { name: 'subtitle', type: 'string', description: 'Subtitle text displayed below the label' },
      { name: 'error', type: 'string', description: 'Error message displayed below the textarea' },
      { name: 'required', type: 'boolean', default: 'false', description: 'Whether the field is marked as required' },
      { name: 'maxLength', type: 'number', description: 'Maximum character length of the input' },
      { name: 'showCharCount', type: 'boolean', default: 'false', description: 'Whether to display a character count' },
      { name: 'size', type: 'string', default: 'md', description: 'Size variant of the textarea' },
    ],
    cssVars: [
      { name: '--azimuth-color-border', description: 'Textarea border color' },
      { name: '--azimuth-color-surface', description: 'Textarea background' },
      { name: '--azimuth-color-text', description: 'Textarea text color' },
      { name: '--azimuth-shadow-focus', description: 'Focus ring shadow' },
    ],
  },
  {
    name: 'TextBox',
    description: 'A styled read-only text display container with plain and code variants.',
    category: 'composite',
    features: ['Plain and code display variants', 'Read-only content display', 'Styled container'],
    variants: ['plain', 'code'],
    props: [
      { name: 'variant', type: 'string', default: 'plain', description: 'Display variant of the text box' },
      { name: 'children', type: 'ReactNode', description: 'The content of the component' },
    ],
    cssVars: [
      { name: '--azimuth-color-surface', description: 'TextBox background' },
      { name: '--azimuth-color-border', description: 'TextBox border' },
      { name: '--azimuth-font-mono', description: 'Code variant font' },
    ],
  },
  {
    name: 'Toggle',
    description: 'A toggle switch component with label and size options.',
    category: 'primitive',
    features: ['Switch/checkbox appearance with role="switch"', 'Label support', 'Three sizes (sm, md, lg)', 'Controlled or uncontrolled checked state', 'Disabled state'],
    variants: [],
    props: [
      { name: 'label', type: 'string', description: 'The label text displayed next to the toggle' },
      { name: 'size', type: 'string', default: 'md', description: 'The size of the toggle switch' },
      { name: 'disabled', type: 'boolean', description: 'Whether the toggle is disabled' },
      { name: 'checked', type: 'boolean', description: 'Controlled checked state' },
      { name: 'defaultChecked', type: 'boolean', description: 'Default checked state (uncontrolled)' },
      { name: 'onChange', type: '(e: ChangeEvent<HTMLInputElement>) => void', description: 'Callback fired when the toggle value changes' },
    ],
    cssVars: [
      { name: '--azimuth-color-primary', description: 'Checked track color' },
      { name: '--azimuth-color-surface', description: 'Unchecked track color' },
      { name: '--azimuth-color-border-strong', description: 'Track border' },
    ],
  },
  {
    name: 'Tooltip',
    description: 'A hover-triggered tooltip with configurable position and delay.',
    category: 'composite',
    features: ['Four position options (top, bottom, left, right)', 'Configurable show delay', 'Arrow indicator', 'Focus trigger for keyboard users', 'Unique ID for aria-describedby'],
    variants: [],
    props: [
      { name: 'content', type: 'ReactNode', description: 'Content displayed inside the tooltip' },
      { name: 'position', type: 'string', default: 'top', description: 'Position of the tooltip relative to the trigger' },
      { name: 'delay', type: 'number', default: '300', description: 'Delay in milliseconds before the tooltip appears' },
      { name: 'children', type: 'ReactNode', description: 'The content of the component' },
    ],
    cssVars: [
      { name: '--azimuth-color-bg', description: 'Tooltip background' },
      { name: '--azimuth-color-text', description: 'Tooltip text color' },
      { name: '--azimuth-fs-xs', description: 'Tooltip font size' },
    ],
  },
  {
    name: 'TreeList',
    description: 'A hierarchical tree view with expand/collapse, selection, and keyboard navigation.',
    category: 'composite',
    features: ['Nested node expansion/collapse', 'Node selection with controlled mode', 'Keyboard navigation (arrows, home, end)', 'Icon support per node', 'Connecting line display', 'Disabled nodes'],
    variants: [],
    props: [
      { name: 'data', type: 'TreeNode[]', description: 'Array of root-level tree nodes' },
      { name: 'defaultExpanded', type: 'string[]', description: 'IDs of nodes expanded by default' },
      { name: 'selectedId', type: 'string', description: 'ID of the currently selected node (controlled)' },
      { name: 'onSelect', type: '(node: TreeNode) => void', description: 'Callback fired when a node is selected' },
      { name: 'onToggle', type: '(node: TreeNode, expanded: boolean) => void', description: 'Callback fired when a node is expanded or collapsed' },
      { name: 'showLines', type: 'boolean', default: 'false', description: 'Whether to show connecting lines between nodes' },
    ],
    cssVars: [
      { name: '--azimuth-color-primary', description: 'Selected node color' },
      { name: '--azimuth-color-primary-subtle', description: 'Selected node background' },
      { name: '--azimuth-color-border', description: 'Connecting line color' },
    ],
  },
  {
    name: 'BreadcrumbPageHeader',
    description: 'Combines breadcrumbs, page title, description, and action buttons in one component.',
    category: 'composite',
    features: ['Breadcrumb navigation', 'Title + actions row', 'Optional description', 'Slot for additional content'],
    variants: [],
    props: [
      { name: 'title', type: 'string', description: 'Page title text.' },
      { name: 'description', type: 'string', description: 'Optional description below the title.' },
      { name: 'breadcrumbs', type: 'Array<{ label: string; href?: string }>', description: 'Breadcrumb trail items.' },
      { name: 'actions', type: 'ReactNode', description: 'Action buttons rendered on the right of the title.' },
    ],
    cssVars: [
      { name: '--azimuth-fs-h2', description: 'Title font size.' },
      { name: '--azimuth-color-text-secondary', description: 'Description text color.' },
    ],
  },
  {
    name: 'ColorPicker',
    description: 'A color picker with preset swatches and custom CSS color input.',
    category: 'composite',
    features: ['Preset swatch grid', 'Custom color input', 'Keyboard accessible swatches', 'Validates CSS color strings'],
    variants: [],
    props: [
      { name: 'value', type: 'string', description: 'Current color value.' },
      { name: 'onChange', type: '(color: string) => void', description: 'Callback when color changes.' },
      { name: 'presets', type: 'string[]', description: 'Array of preset CSS color values.' },
      { name: 'showInput', type: 'boolean', default: 'true', description: 'Show custom color input field.' },
    ],
    cssVars: [
      { name: '--azimuth-radius-full', description: 'Swatch border radius (circular).' },
    ],
  },
  {
    name: 'Combobox',
    description: 'An autocomplete input with filtered dropdown list following WAI-ARIA combobox pattern.',
    category: 'composite',
    features: ['Text input with real-time filtering', 'Keyboard navigation (arrows, enter, escape)', 'ARIA combobox pattern', 'Custom empty state message'],
    variants: [],
    props: [
      { name: 'value', type: 'string', description: 'Controlled input value.' },
      { name: 'onChange', type: '(value: string) => void', description: 'Callback when input text changes.' },
      { name: 'options', type: 'ComboboxOption[]', description: 'Available options for filtering.' },
      { name: 'onSelect', type: '(value: string) => void', description: 'Callback when an option is selected.' },
      { name: 'label', type: 'string', description: 'Label text for the input.' },
      { name: 'placeholder', type: 'string', default: "'Type to search...'", description: 'Input placeholder.' },
      { name: 'disabled', type: 'boolean', description: 'Whether the input is disabled.' },
      { name: 'error', type: 'string', description: 'Error message displayed below the input.' },
      { name: 'emptyMessage', type: 'string', default: "'No results found'", description: 'Text shown when no options match.' },
    ],
    cssVars: [
      { name: '--azimuth-color-primary', description: 'Selected/highlighted option color.' },
      { name: '--azimuth-color-border', description: 'Dropdown border.' },
    ],
  },
  {
    name: 'CommandPalette',
    description: 'A ⌘K-style command palette modal with fuzzy search and keyboard navigation.',
    category: 'composite',
    features: ['Portal-based modal overlay', 'Grouped results with search filtering', 'Full keyboard navigation', 'Shortcut display in results'],
    variants: [],
    props: [
      { name: 'open', type: 'boolean', description: 'Whether the palette is visible.' },
      { name: 'onClose', type: '() => void', description: 'Callback when the palette requests close.' },
      { name: 'groups', type: 'CommandGroup[]', description: 'Grouped command items.' },
      { name: 'onSelect', type: '(item: CommandItem) => void', description: 'Callback when a command is selected.' },
      { name: 'placeholder', type: 'string', default: "'Search commands...'", description: 'Search input placeholder.' },
    ],
    cssVars: [
      { name: '--azimuth-color-primary-subtle', description: 'Active item background.' },
      { name: '--azimuth-color-overlay', description: 'Backdrop overlay color.' },
    ],
  },
  {
    name: 'DiffViewer',
    description: 'A line-by-line code diff viewer with unified and split view modes.',
    category: 'composite',
    features: ['Unified and split view modes', 'Green/red highlighting for additions/removals', 'Line numbers', 'Change statistics header'],
    variants: [],
    props: [
      { name: 'oldCode', type: 'string', description: 'Original source code.' },
      { name: 'newCode', type: 'string', description: 'Modified source code.' },
      { name: 'language', type: 'string', description: 'Language label displayed in the header.' },
      { name: 'showLineNumbers', type: 'boolean', default: 'true', description: 'Show line numbers.' },
      { name: 'splitView', type: 'boolean', default: 'false', description: 'Side-by-side view mode.' },
      { name: 'maxHeight', type: 'string', description: 'Max height of the diff area.' },
    ],
    cssVars: [
      { name: '--azimuth-color-success-bg', description: 'Added line background.' },
      { name: '--azimuth-color-error-bg', description: 'Removed line background.' },
    ],
  },
  {
    name: 'NotificationBadge',
    description: 'A count badge positioned at the top-right of its child element.',
    category: 'composite',
    features: ['Count display with max overflow', 'Dot mode (small indicator)', 'Positioned at top-right of children', 'Multiple color variants'],
    variants: ['danger', 'accent', 'neutral'],
    props: [
      { name: 'count', type: 'number', description: 'Number to display.' },
      { name: 'max', type: 'number', default: '99', description: 'Maximum count before showing +N.' },
      { name: 'dot', type: 'boolean', default: 'false', description: 'Show as small dot without count.' },
      { name: 'size', type: "'sm' | 'md'", default: "'md'", description: 'Badge size.' },
      { name: 'color', type: "'accent' | 'danger' | 'neutral'", default: "'danger'", description: 'Badge color variant.' },
    ],
    cssVars: [
      { name: '--azimuth-color-error-bg', description: 'Danger badge background.' },
      { name: '--azimuth-radius-full', description: 'Badge border radius (pill).' },
    ],
  },
  {
    name: 'OTPInput',
    description: 'A one-time password input with auto-advancing digit boxes.',
    category: 'composite',
    features: ['Auto-advance to next digit on input', 'Paste support (fills all boxes)', 'Backspace to previous box', 'Arrow key navigation'],
    variants: [],
    props: [
      { name: 'length', type: 'number', default: '4', description: 'Number of digit boxes.' },
      { name: 'value', type: 'string', description: 'Controlled value (digits).' },
      { name: 'onChange', type: '(value: string) => void', description: 'Callback when value changes.' },
      { name: 'disabled', type: 'boolean', description: 'Whether the input is disabled.' },
      { name: 'size', type: "'sm' | 'md' | 'lg'", default: "'md'", description: 'Size of digit boxes.' },
      { name: 'error', type: 'boolean', description: 'Show error state.' },
    ],
    cssVars: [
      { name: '--azimuth-color-primary', description: 'Focused/filled box border color.' },
      { name: '--azimuth-color-error-text', description: 'Error state border color.' },
    ],
  },
  {
    name: 'Rating',
    description: 'A star rating widget with keyboard navigation and hover preview.',
    category: 'composite',
    features: ['Click to rate', 'Hover preview', 'Keyboard navigation (arrows, enter)', 'Customizable max value', 'Disabled state'],
    variants: [],
    props: [
      { name: 'value', type: 'number', default: '0', description: 'Current rating value.' },
      { name: 'max', type: 'number', default: '5', description: 'Maximum rating value.' },
      { name: 'onChange', type: '(value: number) => void', description: 'Callback when rating changes.' },
      { name: 'size', type: "'sm' | 'md' | 'lg'", default: "'md'", description: 'Star size.' },
      { name: 'disabled', type: 'boolean', description: 'Whether the rating is disabled.' },
    ],
    cssVars: [
      { name: '--azimuth-color-accent', description: 'Filled star color.' },
      { name: '--azimuth-color-text-muted', description: 'Empty star color.' },
    ],
  },
  {
    name: 'Sidebar',
    description: 'A collapsible vertical navigation sidebar with nested items.',
    category: 'composite',
    features: ['Collapsed/expanded modes (60px/240px)', 'Hover to expand in collapsed mode', 'Nested expandable sections', 'Active item highlighting', 'Badge counts on items'],
    variants: [],
    props: [
      { name: 'items', type: 'SidebarItem[]', description: 'Navigation items.' },
      { name: 'activeKey', type: 'string', description: 'Key of the currently active item.' },
      { name: 'onSelect', type: '(key: string) => void', description: 'Callback when an item is selected.' },
      { name: 'collapsed', type: 'boolean', description: 'Whether the sidebar is collapsed.' },
      { name: 'onToggle', type: '() => void', description: 'Callback to toggle collapsed state.' },
      { name: 'header', type: 'ReactNode', description: 'Brand/logo area at the top.' },
      { name: 'footer', type: 'ReactNode', description: 'Content at the bottom.' },
    ],
    cssVars: [
      { name: '--azimuth-color-primary-subtle', description: 'Active item background.' },
      { name: '--azimuth-color-primary', description: 'Active item text color.' },
    ],
  },
  {
    name: 'SplitButton',
    description: 'A primary action button with a connected dropdown of alternative actions.',
    category: 'composite',
    features: ['Main action with dropdown toggle', 'Dropdown with danger/disabled options', 'Direction support (bottom/top)', 'Variant and size options'],
    variants: ['primary', 'secondary'],
    props: [
      { name: 'label', type: 'string', description: 'Main button label.' },
      { name: 'onClick', type: '() => void', description: 'Callback for the main action.' },
      { name: 'options', type: 'SplitButtonOption[]', description: 'Dropdown menu options.' },
      { name: 'variant', type: "'primary' | 'secondary'", default: "'primary'", description: 'Button variant.' },
      { name: 'size', type: "'sm' | 'md' | 'lg'", default: "'md'", description: 'Button size.' },
      { name: 'disabled', type: 'boolean', description: 'Whether the button is disabled.' },
      { name: 'direction', type: "'bottom' | 'top'", default: "'bottom'", description: 'Dropdown open direction.' },
    ],
    cssVars: [
      { name: '--azimuth-color-primary', description: 'Primary variant background.' },
      { name: '--azimuth-color-border', description: 'Button border.' },
    ],
  },
  {
    name: 'Timeline',
    description: 'A vertical chronological list of events with dots and connecting lines.',
    category: 'composite',
    features: ['Vertical layout with connecting line', 'Circle dots for each event', 'Optional date and icon per item', 'Default and alternating variants'],
    variants: ['default', 'alternating'],
    props: [
      { name: 'items', type: 'TimelineItem[]', description: 'Timeline event items.' },
      { name: 'variant', type: "'default' | 'alternating'", default: "'default'", description: 'Layout variant.' },
    ],
    cssVars: [
      { name: '--azimuth-color-border', description: 'Connecting line color.' },
      { name: '--azimuth-color-accent', description: 'Dot and icon color.' },
    ],
  },
];
